name: build-and-deploy-test
run-name: ${{ github.actor }} is build and deploying new version to test
on:
  push:
    branches:
      feature/build-and-deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      source-directory: ./functions
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.source-directory}}

      - name: Build
        run: npm run build
        working-directory: ${{env.source-directory}}

      - name: Authenticate Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.TEST_GCP_DEPLOYMENT_KEY}}

      - name: Deploy
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'NewReservationHook'
          project_id: '${{vars.TEST_GCP_PROJECT_ID}}'
          runtime: 'nodejs16'
          source_dir: ${{env.source-directory}}
          env_vars: 'GCP_PROJECT_ID=${{vars.TEST_GCP_PROJECT_ID}},GCP_RESERVATION_TOPIC_ID=${{vars.TEST_GCP_TOPIC_NAME}}'